---
# Reference:
# https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-16.04/cuda/8.0/runtime/cudnn5/Dockerfile

- name: Check whether cuDNN exists or not
  stat: path=/usr/local/cuda/include/cudnn.h
  register: cudnn_header

- name: Download cuDNN
  get_url:
    url: http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz
    dest: /tmp/cudnn-8.0-linux-x64-v5.1.tgz
    checksum: sha256:a87cb2df2e5e7cc0a05e266734e679ee1a2fadad6f06af82a76ed81a23b102c8
  when: not cudnn_header.stat.exists

- unarchive: creates=/usr/local/cuda/include/cudnn.h src=/tmp/cudnn-8.0-linux-x64-v5.1.tgz dest=/usr/local
- file: path=/tmp/cudnn-8.0-linux-x64-v5.1.tgz state=absent
